export const initialEmployees = [
    {
      id: 1,
      name: "Bob",
      skills: ["bartender"],
      availability: true,
      performance: 4.8,
      notes:
        "Anchors the Friday/Saturday bar rush. Keeps wells organized, tickets moving quickly, and remembers regulars by name. Occasionally needs a reminder to log 86’d items in the POS, but guest experience scores stay consistently high.",
    },
    {
      id: 2,
      name: "Linda",
      skills: ["bartender"],
      availability: true,
      performance: 4.3,
      notes:
        "Reliable opener who keeps bar prep ahead of the curve. Strong wine and spirits knowledge and double-checks orders before sending.",
    },
    {
      id: 3,
      name: "Cathy",
      skills: ["runner"],
      availability: true,
      performance: 4.9,
      notes:
        "Fastest food runner on the team. Tickets almost never sit in the window and hot food goes out at the right temp.",
    },
    {
      id: 4,
      name: "Alice",
      skills: ["runner", "server"],
      availability: true,
      performance: 4.6,
      notes:
        "Hybrid runner/server who calmly handles high-pressure sections and teaches newer staff expo and ticket reading.",
    },
    {
      id: 5,
      name: "Elissa",
      skills: ["runner"],
      availability: true,
      performance: 4.2,
      notes:
        "Dependable mid-shift runner who keeps side stations stocked and communicates clearly with servers.",
    },
    {
      id: 6,
      name: "Carol",
      skills: ["runner"],
      availability: true,
      performance: 4.7,
      notes:
        "High-energy runner, especially strong on busy patio nights. Reads the room well and prioritizes kids’ food and hot plates.",
    },
    {
      id: 7,
      name: "Mike",
      skills: ["server"],
      availability: true,
      performance: 4.4,
      notes:
        "Guest-facing server with great table-side presence and strong upsell instincts on appetizers and desserts.",
    },
    {
      id: 8,
      name: "Sam",
      skills: ["dishwasher"],
      availability: true,
      performance: 4.1,
      notes:
        "Steady dishwasher who keeps the dish pit under control even when the dining room is full.",
    },
    {
      id: 9,
      name: "Ethan",
      skills: ["server"],
      availability: true,
      performance: 4.3,
      notes:
        "Calm, detail-oriented server who rarely misrings orders and explains menu changes clearly to guests.",
    },
    {
      id: 10,
      name: "Vivian",
      skills: ["server"],
      availability: true,
      performance: 4.7,
      notes:
        "Consistently one of the top tip earners, manages large sections without sacrificing hospitality.",
    },
    {
      id: 11,
      name: "Jordan",
      skills: ["host"],
      availability: true,
      performance: 4.5,
      notes:
        "Smooth on the door, balances walk-ins and reservations without double-seating the same server.",
    },
    {
      id: 12,
      name: "Nina",
      skills: ["host", "runner"],
      availability: true,
      performance: 4.2,
      notes:
        "Helps quote realistic wait times and jumps in as a runner when the board starts to back up.",
    },
    {
      id: 13,
      name: "Leo",
      skills: ["bartender", "server"],
      availability: true,
      performance: 4.6,
      notes:
        "Strong with classic cocktails and can cover a small section of tables when bar is slow.",
    },
    {
      id: 14,
      name: "Grace",
      skills: ["server"],
      availability: true,
      performance: 4.0,
      notes:
        "Very friendly with guests, still building speed with large parties but takes feedback well.",
    },
    {
      id: 15,
      name: "Oscar",
      skills: ["dishwasher", "busser"],
      availability: true,
      performance: 4.1,
      notes:
        "Keeps glassware and plates circulating and will bus the patio when inside volume is low.",
    },
    {
      id: 16,
      name: "Riley",
      skills: ["busser", "runner"],
      availability: true,
      performance: 3.9,
      notes:
        "Good eye for dirty tables and side-work, needs occasional reminders on polishing standards.",
    },
    {
      id: 17,
      name: "Hannah",
      skills: ["server", "runner"],
      availability: true,
      performance: 4.3,
      notes:
        "Handles allergy questions carefully and double-checks with the kitchen before promising substitutions.",
    },
    {
      id: 18,
      name: "Diego",
      skills: ["chef"],
      availability: true,
      performance: 4.8,
      notes:
        "Line lead on busy nights, calls the board clearly and keeps expo organized.",
    },
    {
      id: 19,
      name: "Mia",
      skills: ["chef"],
      availability: true,
      performance: 4.4,
      notes:
        "Strong on grill and sauté, can pivot between stations when tickets spike.",
    },
    {
      id: 20,
      name: "Ivy",
      skills: ["host"],
      availability: true,
      performance: 4.1,
      notes:
        "Warm greeting at the door, good at managing waitlist expectations on busy weekends.",
    },
    {
      id: 21,
      name: "Thomas",
      skills: ["server"],
      availability: true,
      performance: 3.8,
      notes:
        "Still learning the menu, but has solid instincts with guest recovery when mistakes happen.",
    },
    {
      id: 22,
      name: "Paula",
      skills: ["runner", "busser"],
      availability: true,
      performance: 4.0,
      notes:
        "Keeps water and bread service consistent and resets large tables quickly.",
    },
    {
      id: 23,
      name: "Yuri",
      skills: ["bartender"],
      availability: true,
      performance: 4.2,
      notes:
        "Fast with beer and wine service, gradually building confidence with complex cocktails.",
    },
    {
      id: 24,
      name: "Kevin",
      skills: ["dishwasher"],
      availability: true,
      performance: 3.9,
      notes:
        "Quiet but steady, rarely calls out and manages closing duties without reminders.",
    },
    {
      id: 25,
      name: "Chloe",
      skills: ["server", "host"],
      availability: true,
      performance: 4.5,
      notes:
        "Can float between host stand and a small section of tables when staffing is tight.",
    },
    {
      id: 26,
      name: "Noah",
      skills: ["runner"],
      availability: true,
      performance: 3.7,
      notes:
        "Learning table numbers but moves quickly and always checks ticket modifiers with expo.",
    },
    {
      id: 27,
      name: "Sophia",
      skills: ["server"],
      availability: true,
      performance: 4.6,
      notes:
        "High check averages and strong wine sales, especially with date-night tables.",
    },
    {
      id: 28,
      name: "Jason",
      skills: ["busser"],
      availability: true,
      performance: 3.8,
      notes:
        "Keeps floor clear and supports hosts by resetting bar tops during rushes.",
    },
    {
      id: 29,
      name: "Emily",
      skills: ["runner", "server"],
      availability: true,
      performance: 4.4,
      notes:
        "Trustworthy with VIP tables, communicates clearly with both kitchen and bar.",
    },
    {
      id: 30,
      name: "Liam",
      skills: ["bartender", "runner"],
      availability: true,
      performance: 4.3,
      notes:
        "Helps with bar prep before service and occasionally runs food when tickets back up.",
    },
  ];
  
  export const initialTasks = [
    {
      id: 1,
      title: "Prep bar area",
      assignedTo: "Bob",
      status: "in-progress",
      section: "Bar",
      timestamp: "18:30",
      photo: "bar.jpg",
    },
    {
      id: 2,
      title: "Check table 12 cleanup",
      assignedTo: "Cathy",
      status: "pending",
      section: "Dining",
      timestamp: "18:45",
      photo: null,
    },
    {
      id: 3,
      title: "Restock utensils",
      assignedTo: "Alice",
      status: "completed",
      section: "Kitchen",
      timestamp: "18:15",
      photo: "utensils.jpg",
      verified: true,
    },
    {
      id: 4,
      title: "Clean espresso machine",
      assignedTo: null,
      status: "pending",
      section: "Bar",
      timestamp: "19:00",
      photo: null,
    },
    {
      id: 5,
      title: "Set up outdoor seating",
      assignedTo: "Carol",
      status: "in-progress",
      section: "Outdoor",
      timestamp: "18:20",
      photo: "outdoor.jpg",
    },
    {
      id: 6,
      title: "Take out trash",
      assignedTo: "Sam",
      status: "completed",
      section: "Kitchen",
      timestamp: "18:50",
      photo: "trash.jpg",
      verified: true,
    },
    {
      id: 7,
      title: "Polish wine glasses",
      assignedTo: "Oscar",
      status: "pending",
      section: "Bar",
      timestamp: "17:45",
      photo: null,
    },
    {
      id: 8,
      title: "Reset patio heaters",
      assignedTo: "Carol",
      status: "pending",
      section: "Outdoor",
      timestamp: "19:10",
      photo: null,
    },
    {
      id: 9,
      title: "Refill ice bins",
      assignedTo: "Leo",
      status: "in-progress",
      section: "Bar",
      timestamp: "18:10",
      photo: null,
    },
    {
      id: 10,
      title: "Check restroom supplies",
      assignedTo: "Nina",
      status: "pending",
      section: "Dining",
      timestamp: "17:30",
      photo: null,
    },
    {
      id: 11,
      title: "Label prep containers",
      assignedTo: "Mia",
      status: "pending",
      section: "Kitchen",
      timestamp: "16:50",
      photo: null,
    },
    {
      id: 12,
      title: "Deep clean host stand",
      assignedTo: "Jordan",
      status: "pending",
      section: "Dining",
      timestamp: "16:30",
      photo: null,
    },
    {
      id: 13,
      title: "Sweep front entrance",
      assignedTo: "Jason",
      status: "pending",
      section: "Outdoor",
      timestamp: "17:15",
      photo: null,
    },
    {
      id: 14,
      title: "Check heat lamps on line",
      assignedTo: "Diego",
      status: "in-progress",
      section: "Kitchen",
      timestamp: "18:05",
      photo: null,
    },
    {
      id: 15,
      title: "Update 86 list on whiteboard",
      assignedTo: "Bob",
      status: "pending",
      section: "Bar",
      timestamp: "18:40",
      photo: null,
    },
    {
      id: 16,
      title: "Pre-fold napkins for later turn",
      assignedTo: "Riley",
      status: "pending",
      section: "Dining",
      timestamp: "17:20",
      photo: null,
    },
    {
      id: 17,
      title: "Refill kids’ menus and crayons",
      assignedTo: "Ivy",
      status: "pending",
      section: "Dining",
      timestamp: "17:10",
      photo: null,
    },
    {
      id: 18,
      title: "Break down recycling",
      assignedTo: "Kevin",
      status: "pending",
      section: "Kitchen",
      timestamp: "19:20",
      photo: null,
    },
  ];
  
  export const initialRoleCapacity = {
    bartender: 2,
    runner: 4,
    server: 3,
    dishwasher: 1,
    host: 2,
    chef: 2,
    busser: 2,
  };
  